"""schema inicial — todas as tabelas

Revision ID: 816887a17e61
Revises: 
Create Date: 2026-04-03 23:52:34.208132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '816887a17e61'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sqlmodel.sql.sqltypes.AutoString(length=18), nullable=False),
    sa.Column('razao_social', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('regime', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('cnae_principal', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('uf_origem', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('faturamento_12m', sa.TEXT(), nullable=False),
    sa.Column('folha_salarios_12m', sa.TEXT(), nullable=True),
    sa.Column('anexo_simples', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_empresas_cnpj'), ['cnpj'], unique=True)

    op.create_table('alertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('competencia', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
    sa.Column('nivel', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('mensagem', sa.TEXT(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('resolvido_em', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resolvido_por', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('acao_tomada', sa.TEXT(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alertas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alertas_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('atividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('competencia', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
    sa.Column('receita', sa.TEXT(), nullable=False),
    sa.Column('anexo', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('icms_st', sa.Boolean(), nullable=False),
    sa.Column('iss_retido', sa.Boolean(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('atividades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_atividades_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('diagnosticos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('competencia', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
    sa.Column('resultado_json', sa.TEXT(), nullable=False),
    sa.Column('das_mensal', sa.TEXT(), nullable=False),
    sa.Column('aliquota_efetiva', sa.TEXT(), nullable=False),
    sa.Column('rbt12_usado', sa.TEXT(), nullable=False),
    sa.Column('regime_no_calculo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('das_ecac_referencia', sa.TEXT(), nullable=True),
    sa.Column('delta', sa.TEXT(), nullable=True),
    sa.Column('status_auditoria', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diagnosticos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnosticos_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('empresa_historico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('campo_alterado', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('valor_anterior', sa.TEXT(), nullable=True),
    sa.Column('valor_novo', sa.TEXT(), nullable=False),
    sa.Column('alterado_por', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('alterado_em', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('motivo', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('empresa_historico', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_empresa_historico_empresa_id'), ['empresa_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('must_change_password')

    with op.batch_alter_table('empresa_historico', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empresa_historico_empresa_id'))

    op.drop_table('empresa_historico')
    with op.batch_alter_table('diagnosticos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnosticos_empresa_id'))

    op.drop_table('diagnosticos')
    with op.batch_alter_table('atividades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_atividades_empresa_id'))

    op.drop_table('atividades')
    with op.batch_alter_table('alertas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alertas_empresa_id'))

    op.drop_table('alertas')
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empresas_cnpj'))

    op.drop_table('empresas')
    # ### end Alembic commands ###
